"""game table

Revision ID: 76449878269b
Revises: 
Create Date: 2020-01-29 10:11:39.080021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76449878269b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('highscore', sa.String(), nullable=True),
    sa.Column('highscore_aciver', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_name'), 'game', ['name'], unique=True)
    op.create_index(op.f('ix_game_url'), 'game', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_url'), table_name='game')
    op.drop_index(op.f('ix_game_name'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
