"""non-unique-url

Revision ID: d969346855b9
Revises: 76449878269b
Create Date: 2020-01-29 10:34:53.219275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd969346855b9'
down_revision = '76449878269b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_url', table_name='game')
    op.create_index(op.f('ix_game_url'), 'game', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_url'), table_name='game')
    op.create_index('ix_game_url', 'game', ['url'], unique=1)
    # ### end Alembic commands ###
